spring:
  # JPA configuration for database interactions
  jpa:
    show-sql: true  # Show SQL queries in logs
    hibernate:
      ddl-auto: none  # Prevent Hibernate from auto-managing schema
    properties:
      hibernate:
        format-sql: true  # Format SQL for better readability

  # DataSource configuration for MySQL database
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/microservices?serverTimezone=UTC&cachePrepStmts=true&useServerPrepStmts=true&rewriteBatchedStatements=true
    username: root  # Database username
    password: tiger  # Database password
